-- 코드를 입력하세요
-- 0612
-- 1. 음식 종류별 
-- 2. 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)

GROUP BY FOOD_TYPE 
ORDER BY FOOD_TYPE DESC ;
