-- 코드를 입력하세요
-- 0611
-- 조건 1 09:00부터 19:59까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회 
-- 조건 2 시간대 순으로 정렬
-- 
SELECT HOUR(DATETIME) AS HOUR,	COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >=9 AND HOUR <=19
ORDER  BY  HOUR(DATETIME)

