-- 코드를 입력하세요
-- 0610

SELECT A.FLAVOR FROM FIRST_HALF AS A LEFT JOIN ICECREAM_INFO AS B
ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE= 'FRUIT_BASED'
ORDER BY A.TOTAL_ORDER DESC




-- SELECT F.FLAVOR,TOTAL_ORDER FROM FIRST_HALF F INNER JOIN ICECREAM_INFO I 
-- ON F.FLAVOR = I.FLAVOR